server:
  port: 8080

spring:
  mvc:
    servlet:
      path: /
  application:
    name: atv-sinc1
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # Cria e remove as tabelas no início e no fim da execução
    show-sql: true # Mostra as queries SQL no console
    defer-datasource-initialization: true # Adia a inicialização do banco de dados para depois do JPA
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # Define o dialeto do Hibernate para H2
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true # Ativa o console H2
      path: /h2-console # Define o caminho do console H2
